-- Clear existing channels (cascade if necessary, though we are removing category dependency)
TRUNCATE TABLE strategy_channels CASCADE;

-- Insert flat list of channels
INSERT INTO strategy_channels (name) VALUES
('Social Media - Organic - LinkedIn'),
('Social Media - Organic - Facebook'),
('Social Media - Organic - Instagram'),
('Social Media - Organic - Twitter/X'),
('Social Media - Organic - YouTube'),
('Social Media - Organic - TikTok'),
('Social Media - Organic - Pinterest'),
('Social Media - Organic - Reddit'),
('Social Media - Organic - Quora'),
('Social Media - Organic - Medium'),
('Social Media - Organic - Threads'),
('Social Media - Paid - LinkedIn Ads'),
('Social Media - Paid - Facebook Ads'),
('Social Media - Paid - Instagram Ads'),
('Social Media - Paid - Twitter/X Ads'),
('Social Media - Paid - YouTube Ads'),
('Social Media - Paid - TikTok Ads'),
('Social Media - Paid - Pinterest Ads'),
('Social Media - Paid - Reddit Ads'),
('Social Media - Paid - Quora Ads'),
('Social Media - Paid - Snapchat Ads'),
('Search - Google Search (Organic/SEO)'),
('Search - Google Ads (Search)'),
('Search - Bing Search (Organic/SEO)'),
('Search - Bing Ads'),
('Display & Programmatic - Google Display Network'),
('Display & Programmatic - Programmatic Display Advertising'),
('Display & Programmatic - Native Advertising Networks'),
('Display & Programmatic - Account-Based Display (ABM Platforms)'),
('Display & Programmatic - Retargeting/Remarketing'),
('Email - Email Marketing (Owned List)'),
('Email - Cold Email Outreach'),
('Email - Sponsored Newsletters'),
('Email - Newsletter Sponsorships (Substack, beehiiv, Morning Brew)'),
('Content Marketing - Company Blog'),
('Content Marketing - Guest Blogging'),
('Content Marketing - White Papers'),
('Content Marketing - E-books'),
('Content Marketing - Case Studies'),
('Content Marketing - Research Reports'),
('Content Marketing - Webinars (Owned)'),
('Content Marketing - Podcasts (Owned)'),
('Content Marketing - Video Content (Owned Channel)'),
('Content Marketing - Infographics'),
('Content Marketing - SlideShare'),
('Review & Comparison Sites - G2'),
('Review & Comparison Sites - Capterra'),
('Review & Comparison Sites - TrustRadius'),
('Review & Comparison Sites - Gartner Peer Insights'),
('Review & Comparison Sites - Clutch.co'),
('Review & Comparison Sites - Product Hunt'),
('Review & Comparison Sites - Trustpilot'),
('Review & Comparison Sites - Better Business Bureau (BBB)'),
('Review & Comparison Sites - Glassdoor (Company Reviews)'),
('Content Syndication - TechTarget'),
('Content Syndication - Demandbase'),
('Content Syndication - NetLine Portal'),
('Content Syndication - Madison Logic'),
('Content Syndication - Industry-Specific Content Networks'),
('Communities & Forums - Slack Communities'),
('Communities & Forums - Discord Communities'),
('Communities & Forums - Industry-Specific Forums'),
('Communities & Forums - Stack Overflow'),
('Communities & Forums - LinkedIn Groups'),
('Communities & Forums - Facebook Groups'),
('Communities & Forums - Reddit Communities'),
('Communities & Forums - Alignable'),
('Messaging Platforms - WhatsApp Business'),
('Messaging Platforms - Telegram Channels'),
('Messaging Platforms - SMS Marketing'),
('Messaging Platforms - Facebook Messenger'),
('Events & Conferences - Trade Shows (Booth)'),
('Events & Conferences - Trade Shows (Sponsorship)'),
('Events & Conferences - Industry Conferences (Speaking)'),
('Events & Conferences - Industry Conferences (Sponsorship)'),
('Events & Conferences - Virtual Events'),
('Events & Conferences - Webinars (Third-Party/Sponsored)'),
('Events & Conferences - Executive Roundtables'),
('Events & Conferences - Networking Events'),
('Podcasts - Podcast Sponsorships'),
('Podcasts - Podcast Guest Appearances'),
('Podcasts - Your own'),
('Sales Outreach - Cold Calling'),
('Sales Outreach - LinkedIn Sales Navigator'),
('Sales Outreach - Video Prospecting'),
('Sales Outreach - Direct Mail (Personalized)'),
('Sales Outreach - Dimensional Mail/Gifting'),
('Partnerships & Channels - Co-Marketing with Partners'),
('Partnerships & Channels - Technology Partner Directories'),
('Partnerships & Channels - Reseller/Channel Partners'),
('Partnerships & Channels - Affiliate Programs'),
('Partnerships & Channels - Referral Programs'),
('Public Relations & Media - Press Releases'),
('Public Relations & Media - Media Outreach'),
('Public Relations & Media - Industry Analyst Relations'),
('Public Relations & Media - Trade Publications (Bylined Articles)'),
('Public Relations & Media - HARO/Media Opportunities'),
('Public Relations & Media - Sponsored Content (Forbes, HBR, Inc., Entrepreneur)'),
('Traditional Media - Business TV (CNBC, Bloomberg)'),
('Traditional Media - Business Radio'),
('Traditional Media - Trade Publications (Print Ads)'),
('Traditional Media - Trade Publications (Digital Ads)'),
('Traditional Media - Business Newspapers (WSJ, FT)'),
('Traditional Media - Industry Magazines'),
('Out of Home - Airport Advertising'),
('Out of Home - Business District Billboards'),
('Out of Home - Transit Advertising'),
('Out of Home - Airport Lounges'),
('Out of Home - Hotel Business Centers'),
('Streaming & Audio - Spotify Ads'),
('Streaming & Audio - Pandora Ads'),
('Streaming & Audio - Streaming Audio Platforms'),
('Streaming & Audio - Connected TV (CTV)'),
('Video Platforms - Vimeo'),
('Video Platforms - Wistia'),
('Video Platforms - Twitch'),
('Marketplace & Platform Listings - AWS Marketplace'),
('Marketplace & Platform Listings - Microsoft AppSource'),
('Marketplace & Platform Listings - Google Workspace Marketplace'),
('Marketplace & Platform Listings - Shopify App Store'),
('Marketplace & Platform Listings - Salesforce AppExchange'),
('Marketplace & Platform Listings - HubSpot Marketplace'),
('Marketplace & Platform Listings - Zoom Apps Marketplace'),
('Marketplace & Platform Listings - Slack App Directory'),
('B2B Marketplaces - Amazon Business'),
('B2B Marketplaces - Alibaba'),
('B2B Marketplaces - ThomasNet'),
('Local & Directories - Google Business Profile'),
('Local & Directories - Bing Places'),
('Local & Directories - Apple Maps Business'),
('Local & Directories - Yelp for Business'),
('Local & Directories - Local Chamber of Commerce'),
('Local & Directories - Yellow Pages (Business)'),
('Industry Associations - Association Memberships/Directories'),
('Industry Associations - Association Newsletters'),
('Industry Associations - Association Webinars'),
('Industry Associations - Association Awards'),
('Lead Generation & Data - ZoomInfo'),
('Lead Generation & Data - Apollo.io'),
('Lead Generation & Data - Cognism'),
('Lead Generation & Data - Clearbit'),
('Lead Generation & Data - LinkedIn Sales Navigator Database'),
('Intent Data & ABM - Bombora'),
('Intent Data & ABM - 6sense'),
('Intent Data & ABM - Demandbase'),
('Intent Data & ABM - Terminus'),
('News & Media Sites - Industry News Sites (TechCrunch, VentureBeat, etc.)'),
('News & Media Sites - Business Insider'),
('News & Media Sites - Axios'),
('News & Media Sites - Bloomberg'),
('News & Media Sites - Reuters'),
('Educational & Training - Coursera (Corporate Training)'),
('Educational & Training - LinkedIn Learning'),
('Educational & Training - Udemy Business'),
('Educational & Training - Industry Certification Programs'),
('Educational & Training - University Partnerships'),
('Job Boards (Employer Branding) - LinkedIn Jobs (Employer Brand)'),
('Job Boards (Employer Branding) - Indeed (Employer Brand)'),
('Job Boards (Employer Branding) - Built In'),
('Analyst & Research Firms - Gartner'),
('Analyst & Research Firms - Forrester'),
('Analyst & Research Firms - IDC'),
('Analyst & Research Firms - Industry-Specific Analysts'),
('Customer Advocacy - Customer Referral Programs'),
('Customer Advocacy - Customer Advocacy Programs'),
('Customer Advocacy - Review Generation Campaigns'),
('Customer Advocacy - Case Study Programs'),
('Customer Advocacy - Testimonial Programs'),
('Community Building - Private Online Communities'),
('Community Building - User Groups (Regional/Virtual)'),
('Community Building - Customer Events'),
('Community Building - Training/Certification Programs'),
('Sponsored Opportunities - Industry Awards Sponsorship'),
('Sponsored Opportunities - Research Report Sponsorship'),
('Sponsored Opportunities - Charity Events (B2B Networking)'),
('Sponsored Opportunities - Sports/Golf Tournaments'),
('Sponsored Opportunities - Executive Retreats'),
('Financial & Business Platforms - Crunchbase'),
('Financial & Business Platforms - PitchBook'),
('Financial & Business Platforms - AngelList'),
('Financial & Business Platforms - CB Insights'),
('Developer-Focused (for tech B2B) - GitHub'),
('Developer-Focused (for tech B2B) - Stack Overflow'),
('Developer-Focused (for tech B2B) - Developer Conferences'),
('Developer-Focused (for tech B2B) - Hackathons'),
('Communication & Collaboration Tools - Microsoft Teams Integrations'),
('Communication & Collaboration Tools - Google Chat Apps'),
('Communication & Collaboration Tools - Zoom Integrations'),
('Web & Mobile - Web Push Notifications'),
('Web & Mobile - Mobile App Push Notifications'),
('Web & Mobile - Chatbots/Live Chat'),
('Web & Mobile - Exit-Intent Popups'),
('Presentation & Documentation - SlideShare'),
('Presentation & Documentation - Speaker Deck'),
('Presentation & Documentation - Public Documentation Sites'),
('Voice & Emerging - Voice Assistants (Alexa Skills, Google Actions)'),
('Voice & Emerging - Smart Speaker Advertising'),
('Retargeting Specific - Website Retargeting'),
('Retargeting Specific - LinkedIn Matched Audiences'),
('Retargeting Specific - Facebook Custom Audiences'),
('Retargeting Specific - Google Customer Match');
